version: '3'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shoeshop
      MYSQL_DATABASE: shoeshop
    volumes:
      - db_data:/var/lib/mysql
      - ./shoe_shopdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  app:
    image: shoeshop
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
volumes:
  db_data:
